#!/usr/bin/env python3
"""Reconcile an independent 65816disasm pass with the closed V35 authority.

The external disassembler is deliberately treated as a candidate generator, not
as truth.  Every external start is classified against the exact ROM bytes and
the context-aware fixed-point manifest.  Strictly unclassified candidates can
also be emitted as a short, bounded Mesen headless-oracle script.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
from collections import Counter
from pathlib import Path


INSTRUCTION_RE = re.compile(
    r"^\s+[^;\r\n]+;\s*\$([0-9A-Fa-f]+)(?:\s*(?:\||$))"
)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def read_external_diagnostic(path: Path) -> str:
    raw = path.read_bytes()
    if raw.startswith((b"\xff\xfe", b"\xfe\xff")):
        return raw.decode("utf-16").strip()
    return raw.decode("utf-8", errors="replace").strip()


def parse_cpu_address(text: str) -> tuple[int, int]:
    bank, pc = text.split(":")
    return int(bank, 16), int(pc, 16)


def mirror_address(address: int, size: int) -> int:
    base = 0
    mask = 1 << (max(address, size - 1).bit_length() - 1)
    while address >= size:
        while mask and not (address & mask):
            mask >>= 1
        if not mask:
            return base + (address % size)
        address -= mask
        if size > mask:
            size -= mask
            base += mask
        mask >>= 1
    return base + address


def cpu_to_offset(bank: int, address: int, size: int) -> int | None:
    bank &= 0xFF
    address &= 0xFFFF
    if bank in (0x7E, 0x7F):
        return None
    if bank <= 0x3F or 0x80 <= bank <= 0xBF:
        if address < 0x8000:
            return None
        linear = ((bank & 0x3F) << 16) | address
    elif 0x40 <= bank <= 0x7D or 0xC0 <= bank <= 0xFF:
        linear = ((bank & 0x3F) << 16) | address
    else:
        return None
    return mirror_address(linear, size)


def aliases_for_offset(offset: int) -> list[int]:
    """Return all direct HiROM CPU aliases for this physical offset."""
    bank = offset >> 16
    pc = offset & 0xFFFF
    aliases = {
        ((0x40 + bank) << 16) | pc,
        ((0xC0 + bank) << 16) | pc,
    }
    if pc >= 0x8000:
        aliases.add((bank << 16) | pc)
        aliases.add(((0x80 + bank) << 16) | pc)
    return sorted(aliases)


def merged_clusters(offsets: list[int], maximum_gap: int = 4) -> list[dict]:
    if not offsets:
        return []
    clusters = []
    start = previous = offsets[0]
    count = 1
    for offset in offsets[1:]:
        if offset - previous <= maximum_gap:
            previous = offset
            count += 1
            continue
        clusters.append({
            "start": f"0x{start:06X}",
            "end_inclusive": f"0x{previous:06X}",
            "candidate_starts": count,
        })
        start = previous = offset
        count = 1
    clusters.append({
        "start": f"0x{start:06X}",
        "end_inclusive": f"0x{previous:06X}",
        "candidate_starts": count,
    })
    return clusters


def emit_mesen_script(path: Path, candidate_offsets: list[int]) -> None:
    aliases: dict[int, int] = {}
    for offset in candidate_offsets:
        for address in aliases_for_offset(offset):
            aliases[address] = offset

    lines = [
        "-- Generated by audit_v35_independent_disassembler.py.",
        "-- Bounded MesenCE headless oracle; observations are not static authority.",
        "local candidates = {",
    ]
    for address, offset in sorted(aliases.items()):
        lines.append(f"  [0x{address:06X}] = 0x{offset:06X},")
    lines.extend([
        "}",
        "local instruction_count = 0",
        "local unique_count = 0",
        "local unique_hash = 2166136261",
        "local seen = {}",
        "local hits = {}",
        "local hit_count = 0",
        "local frame_count = 0",
        "local finished = false",
        "local function finish(reason)",
        "  if finished then return end",
        "  finished = true",
        "  local hit_offsets = {}",
        "  for offset, _ in pairs(hits) do table.insert(hit_offsets, offset) end",
        "  table.sort(hit_offsets)",
        "  local rendered = {}",
        "  for _, offset in ipairs(hit_offsets) do",
        "    table.insert(rendered, string.format(\"%06X\", offset))",
        "  end",
        "  local message = string.format(\"V35_HEADLESS_ORACLE reason=%s frames=%d instructions=%d unique_pc=%d unique_hash=%08X candidate_physical_hits=%d hit_offsets=%s\", reason, frame_count, instruction_count, unique_count, unique_hash, hit_count, table.concat(rendered, \",\"))",
        "  print(message)",
        "  emu.log(message)",
        "  emu.stop(0)",
        "end",
        "local function on_exec(address, value)",
        "  instruction_count = instruction_count + 1",
        "  if not seen[address] then",
        "    seen[address] = true",
        "    unique_count = unique_count + 1",
        "    unique_hash = (unique_hash * 16777619 + address) % 4294967296",
        "  end",
        "  local offset = candidates[address]",
        "  if offset and not hits[offset] then",
        "    hits[offset] = true",
        "    hit_count = hit_count + 1",
        "  end",
        "  if instruction_count >= 250000 then finish(\"instruction-limit\") end",
        "end",
        "local function on_end_frame()",
        "  frame_count = frame_count + 1",
        "  if frame_count >= 3 then finish(\"frame-limit\") end",
        "end",
        "emu.addMemoryCallback(on_exec, emu.callbackType.exec, 0, 0xFFFFFF, emu.cpuType.snes, emu.memType.snesMemory)",
        "emu.addEventCallback(on_end_frame, emu.eventType.endFrame)",
        "local start_message = string.format(\"V35_HEADLESS_ORACLE_START candidate_offsets=%d candidate_aliases=%d\", " + str(len(candidate_offsets)) + ", " + str(len(aliases)) + ")",
        "print(start_message)",
        "emu.log(start_message)",
    ])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("rom", type=Path)
    parser.add_argument("--analysis", type=Path, required=True)
    parser.add_argument("--external-asm", type=Path, required=True)
    parser.add_argument("--external-stderr", type=Path)
    parser.add_argument("--classification", type=Path)
    parser.add_argument("--output-json", type=Path, required=True)
    parser.add_argument("--output-text", type=Path, required=True)
    parser.add_argument("--output-mesen-lua", type=Path)
    args = parser.parse_args()

    raw = args.rom.read_bytes()
    analysis = json.loads(args.analysis.read_text(encoding="utf-8"))
    if analysis.get("rom_sha256") != hashlib.sha256(raw).hexdigest():
        raise SystemExit("Analysis manifest and ROM SHA-256 do not match")

    current_starts: set[int] = set()
    current_bytes: set[int] = set()
    for row in analysis.get("contexts", []):
        bank, pc = parse_cpu_address(row["address"])
        offset = cpu_to_offset(bank, pc, len(raw))
        if offset is None:
            continue
        current_starts.add(offset)
        encoded = bytes.fromhex(row["bytes"])
        for index in range(len(encoded)):
            current_bytes.add((offset + index) % len(raw))

    external_starts: set[int] = set()
    parsed_line_count = 0
    for line in args.external_asm.read_text(encoding="utf-8", errors="replace").splitlines():
        match = INSTRUCTION_RE.match(line)
        if not match:
            continue
        parsed_line_count += 1
        offset = int(match.group(1), 16)
        if offset < len(raw):
            external_starts.add(offset)

    physical_classes: dict[int, str] = {}
    if args.classification:
        classification = json.loads(args.classification.read_text(encoding="utf-8"))
        for row in classification.get("physical_class_ranges", []):
            start = int(row["start"], 16)
            end = int(row["end_exclusive"], 16)
            for offset in range(start, end):
                physical_classes[offset] = row["class"]

    categories: dict[str, list[int]] = {
        "MATCHED_CURRENT_START": [],
        "INSIDE_CURRENT_INSTRUCTION_BYTES": [],
        "SNES_HEADER_VECTOR": [],
        "PADDING_CANDIDATE": [],
        "STRICTLY_UNCLASSIFIED_START_CANDIDATE": [],
    }
    for offset in sorted(external_starts):
        if offset in current_starts:
            category = "MATCHED_CURRENT_START"
        elif offset in current_bytes:
            category = "INSIDE_CURRENT_INSTRUCTION_BYTES"
        elif physical_classes.get(offset) == "SNES_HEADER_VECTOR":
            category = "SNES_HEADER_VECTOR"
        elif physical_classes.get(offset) == "PADDING_CANDIDATE":
            category = "PADDING_CANDIDATE"
        else:
            category = "STRICTLY_UNCLASSIFIED_START_CANDIDATE"
        categories[category].append(offset)

    strict = categories["STRICTLY_UNCLASSIFIED_START_CANDIDATE"]
    external_only = sorted(external_starts - current_starts)
    diagnostics = ""
    if args.external_stderr and args.external_stderr.exists():
        diagnostics = read_external_diagnostic(args.external_stderr)

    report = {
        "format": "civilization-v35-independent-disassembler-audit-v1",
        "policy": "candidate-generator-only; no external result is static authority",
        "rom": {
            "bytes": len(raw),
            "sha256": hashlib.sha256(raw).hexdigest(),
        },
        "inputs": {
            "analysis_sha256": sha256(args.analysis),
            "external_asm_sha256": sha256(args.external_asm),
            "external_stderr_sha256": sha256(args.external_stderr) if args.external_stderr and args.external_stderr.exists() else None,
            "classification_sha256": sha256(args.classification) if args.classification else None,
        },
        "counts": {
            "external_instruction_lines": parsed_line_count,
            "external_unique_physical_starts": len(external_starts),
            "current_unique_physical_starts": len(current_starts),
            "common_starts": len(external_starts & current_starts),
            "external_only_starts": len(external_only),
            "current_only_starts": len(current_starts - external_starts),
            **{key.lower(): len(value) for key, value in categories.items()},
        },
        "external_only_classification": {
            key: [f"0x{offset:06X}" for offset in value]
            for key, value in categories.items() if key != "MATCHED_CURRENT_START"
        },
        "strict_candidate_clusters": merged_clusters(strict),
        "external_diagnostics": diagnostics,
        "interpretation": [
            "Matches corroborate starts but do not prove completeness.",
            "Interior-byte starts usually indicate width-state or traversal desynchronization.",
            "Strictly unclassified starts require a second static proof before promotion.",
            "Mesen observations are bounded oracle evidence only and are never imported as authority.",
        ],
    }

    args.output_json.parent.mkdir(parents=True, exist_ok=True)
    args.output_text.parent.mkdir(parents=True, exist_ok=True)
    args.output_json.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")

    counts = report["counts"]
    text = [
        "Civilization V35 Test - Independent Disassembler Reconciliation",
        "================================================================",
        "",
        f"ROM SHA-256: {report['rom']['sha256']}",
        "Policy: external disassembly is candidate generation only.",
        f"External unique starts: {counts['external_unique_physical_starts']:,}",
        f"Current unique starts: {counts['current_unique_physical_starts']:,}",
        f"Common starts: {counts['common_starts']:,}",
        f"External-only starts: {counts['external_only_starts']:,}",
        f"  Inside current instruction bytes: {counts['inside_current_instruction_bytes']:,}",
        f"  SNES header/vector: {counts['snes_header_vector']:,}",
        f"  Padding candidates: {counts['padding_candidate']:,}",
        f"  Strict unclassified candidates: {counts['strictly_unclassified_start_candidate']:,}",
        f"Current-only starts: {counts['current_only_starts']:,}",
        f"Strict candidate clusters: {len(report['strict_candidate_clusters']):,}",
        "",
        "Result",
        "------",
        "No external-only address is promoted automatically. Strict candidates move",
        "to context-aware static review; the bounded Mesen run only checks whether any",
        "appear during the short boot oracle window.",
        "",
        "External diagnostic",
        "-------------------",
        diagnostics or "(none)",
    ]
    args.output_text.write_text("\n".join(text) + "\n", encoding="utf-8")

    if args.output_mesen_lua:
        emit_mesen_script(args.output_mesen_lua, strict)

    print(json.dumps({
        "external_starts": len(external_starts),
        "external_only": len(external_only),
        "strict_candidates": len(strict),
        "strict_clusters": len(report["strict_candidate_clusters"]),
    }, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
