#!/usr/bin/env python3
"""Emit a bounded MesenCE Lua comparator for the closed Civilization S-CPU graph.

Mesen observations are validation evidence only.  The fixed-point manifest remains
the static authority; this tool reports any address observed by Mesen that is not
present in that authority without widening the production graph.
"""

import argparse
import json
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--instruction-limit", type=int, default=60_000_000)
    parser.add_argument("--frame-limit", type=int, default=5_000)
    args = parser.parse_args()

    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    addresses = sorted({int(row["address"].replace(":", ""), 16) for row in manifest["contexts"]})
    lines = [
        "-- Generated by emit_mesen_static_coverage_audit.py.",
        "-- Comparator only: observations never widen the static authority.",
        "local authority = {",
    ]
    lines.extend(f"  [0x{address:06X}] = true," for address in addresses)
    lines.extend(
        [
            "}",
            "local instructions, frames, unique_count, owned_unique = 0, 0, 0, 0",
            "local seen, missing, finished = {}, {}, false",
            "local function finish(reason)",
            "  if finished then return end",
            "  finished = true",
            "  local rows = {}",
            "  for address, _ in pairs(missing) do table.insert(rows, address) end",
            "  table.sort(rows)",
            "  local rendered = {}",
            "  for _, address in ipairs(rows) do table.insert(rendered, string.format(\"%06X\", address)) end",
            "  local message = string.format(\"CIV_STATIC_COVERAGE reason=%s frames=%d instructions=%d unique_pc=%d owned_unique=%d missing_unique=%d missing=%s\", reason, frames, instructions, unique_count, owned_unique, #rows, table.concat(rendered, \",\"))",
            "  print(message)",
            "  emu.log(message)",
            "  emu.stop(#rows == 0 and 0 or 1)",
            "end",
            "local function on_exec(address, value)",
            "  instructions = instructions + 1",
            "  if not seen[address] then",
            "    seen[address] = true",
            "    unique_count = unique_count + 1",
            "    if authority[address] then owned_unique = owned_unique + 1 else missing[address] = true end",
            "  end",
            f"  if instructions >= {args.instruction_limit} then finish(\"instruction-limit\") end",
            "end",
            "local function on_end_frame()",
            "  frames = frames + 1",
            f"  if frames >= {args.frame_limit} then finish(\"frame-limit\") end",
            "end",
            "emu.addMemoryCallback(on_exec, emu.callbackType.exec, 0, 0xFFFFFF, emu.cpuType.snes, emu.memType.snesMemory)",
            "emu.addEventCallback(on_end_frame, emu.eventType.endFrame)",
            f"print(\"CIV_STATIC_COVERAGE_START authority_addresses={len(addresses)}\")",
        ]
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
