#!/usr/bin/env python3
"""Emit a MesenCE Lua comparator for Civilization's finite S-SMP AOT lookup."""

import argparse
import re
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--lookup", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--frame-limit", type=int, default=4_963)
    args = parser.parse_args()

    text = args.lookup.read_text(encoding="utf-8")
    addresses = sorted({int(value, 16) for value in re.findall(r"case 0x([0-9a-fA-F]{4})u:", text)})
    if not addresses:
        raise SystemExit("No S-SMP AOT cases found in lookup")

    lines = [
        "-- Generated by emit_mesen_static_audio_coverage_audit.py.",
        "-- Comparator only: observations never widen the static audio authority.",
        "local authority = {",
    ]
    lines.extend(f"  [0x{address:04X}] = true," for address in addresses)
    lines.extend(
        [
            "}",
            "local frames, instructions, unique_count, owned_unique = 0, 0, 0, 0",
            "local seen, missing, finished = {}, {}, false",
            "local function finish(reason)",
            "  if finished then return end",
            "  finished = true",
            "  local rows = {}",
            "  for address, _ in pairs(missing) do table.insert(rows, address) end",
            "  table.sort(rows)",
            "  local rendered = {}",
            "  for _, address in ipairs(rows) do table.insert(rendered, string.format(\"%04X\", address)) end",
            "  local message = string.format(\"CIV_STATIC_AUDIO_COVERAGE reason=%s frames=%d smp_instructions=%d unique_pc=%d owned_unique=%d missing_unique=%d missing=%s\", reason, frames, instructions, unique_count, owned_unique, #rows, table.concat(rendered, \",\"))",
            "  print(message)",
            "  emu.log(message)",
            "  emu.stop(#rows == 0 and 0 or 1)",
            "end",
            "local function on_spc_exec(address, value)",
            "  instructions = instructions + 1",
            "  if not seen[address] then",
            "    seen[address] = true",
            "    unique_count = unique_count + 1",
            "    if authority[address] then owned_unique = owned_unique + 1 else missing[address] = true end",
            "  end",
            "end",
            "local function on_end_frame()",
            "  frames = frames + 1",
            f"  if frames >= {args.frame_limit} then finish(\"frame-limit\") end",
            "end",
            "emu.addMemoryCallback(on_spc_exec, emu.callbackType.exec, 0, 0xFFFF, emu.cpuType.spc, emu.memType.spcMemory)",
            "emu.addEventCallback(on_end_frame, emu.eventType.endFrame)",
            f"print(\"CIV_STATIC_AUDIO_COVERAGE_START authority_addresses={len(addresses)}\")",
        ]
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
